#+title: Gnu Emacs Config
#+author: sirdonvua

* Table of contents :toc:
- [[#package-mangment][package mangment]]
  - [[#elpaca][Elpaca]]
  - [[#use-package][use-package]]
- [[#keybindings][Keybindings]]
  - [[#evil-mode][EVIL MODE]]
  - [[#general][general]]
- [[#customaization][Customaization]]
  - [[#dashboard][dashboard]]
  - [[#fonts][fonts]]
  - [[#noobie-bars][noobie bars]]
  - [[#theme][theme]]
  - [[#modeline][modeline]]
  - [[#beacon][beacon]]
- [[#emacs-tweaks][emacs tweaks]]
  - [[#-files][~ files]]
  - [[#compiler-messages][Compiler messages]]
  - [[#symlinks][symlinks]]
  - [[#scrolling][scrolling]]
  - [[#zooming-in-and-out][zooming in and out]]
- [[#ivy-and-counsel][Ivy and counsel]]
- [[#dired][dired]]
  - [[#icons][icons]]
  - [[#dired-open][dired-open]]
  - [[#peep-dired][peep-dired]]
  - [[#trash][Trash]]
- [[#org-mode][org mode]]
  - [[#org-headers][org headers]]
  - [[#org-modern][org modern]]
  - [[#syntax-highlighing][Syntax highlighing]]
  - [[#org-tempo][org tempo]]
  - [[#tabel-of-contents][tabel of contents]]
  - [[#org-auto-tangle][org auto Tangle]]
  - [[#org-journal][org journal]]
  - [[#keybindings-1][keybindings]]
- [[#magit][Magit]]
- [[#which-key][Which Key]]
- [[#emacs-ide][Emacs IDE]]
  - [[#lsp][LSP]]
  - [[#company][company]]
  - [[#vterm][Vterm]]
  - [[#smartparens][smartparens]]
  - [[#sudoedit][sudoedit]]
  - [[#rainbow-mode][rainbow mode]]
  - [[#languages-support][Languages support]]

* package mangment
** Elpaca
a better packge manager for Emacs.
*** installing
#+begin_src emacs-lisp

(defvar elpaca-installer-version 0.5)
(defvar elpaca-directory (expand-file-name "elpaca/" user-emacs-directory))
(defvar elpaca-builds-directory (expand-file-name "builds/" elpaca-directory))
(defvar elpaca-repos-directory (expand-file-name "repos/" elpaca-directory))
(defvar elpaca-order '(elpaca :repo "https://github.com/progfolio/elpaca.git"
                              :ref nil
                              :files (:defaults (:exclude "extensions"))
                              :build (:not elpaca--activate-package)))
(let* ((repo  (expand-file-name "elpaca/" elpaca-repos-directory))
       (build (expand-file-name "elpaca/" elpaca-builds-directory))
       (order (cdr elpaca-order))
       (default-directory repo))
  (add-to-list 'load-path (if (file-exists-p build) build repo))
  (unless (file-exists-p repo)
    (make-directory repo t)
    (when (< emacs-major-version 28) (require 'subr-x))
    (condition-case-unless-debug err
        (if-let ((buffer (pop-to-buffer-same-window "*elpaca-bootstrap*"))
                 ((zerop (call-process "git" nil buffer t "clone"
                                       (plist-get order :repo) repo)))
                 ((zerop (call-process "git" nil buffer t "checkout"
                                       (or (plist-get order :ref) "--"))))
                 (emacs (concat invocation-directory invocation-name))
                 ((zerop (call-process emacs nil buffer nil "-Q" "-L" "." "--batch"
                                       "--eval" "(byte-recompile-directory \".\" 0 'force)")))
                 ((require 'elpaca))
                 ((elpaca-generate-autoloads "elpaca" repo)))
            (progn (message "%s" (buffer-string)) (kill-buffer buffer))
          (error "%s" (with-current-buffer buffer (buffer-string))))
      ((error) (warn "%s" err) (delete-directory repo 'recursive))))
  (unless (require 'elpaca-autoloads nil t)
    (require 'elpaca)
    (elpaca-generate-autoloads "elpaca" repo)
    (load "./elpaca-autoloads")))
(add-hook 'after-init-hook #'elpaca-process-queues)
(elpaca `(,@elpaca-order))

#+end_src

*** use-package support
makes elpaca works with use-package
#+begin_src elisp

;; Install use-package support
(elpaca elpaca-use-package
  ;; Enable :elpaca use-package keyword.
  (elpaca-use-package-mode)
  ;; Assume :elpaca t unless otherwise specified.
  (setq elpaca-use-package-by-default t))

;; Block until current queue processed.
(elpaca-wait)

#+end_src

** use-package
an easy way to manage packages in emacs.
#+begin_src emacs-lisp

(require 'use-package-ensure)
(setq use-package-always-ensure t) ; always make sure that the packages are installed

#+end_src

* Keybindings
** EVIL MODE
the Emacs vi layer

for normal text editing:
#+BEGIN_SRC emacs-lisp

(use-package evil
:init ;; tweak the package before loading
(setq evil-want-keybinding nil)
(setq evil-undo-system 'undo-redo)
(evil-mode 1))

#+END_SRC

for some buffers like titrus :)
#+BEGIN_SRC emacs-lisp

(use-package evil-collection
:after evil
:config
(evil-collection-init))

#+END_SRC

learning evil :)
#+begin_src elisp

(use-package evil-tutor)

#+end_src
** general
the general.el package which is an easy way to make keybindings
#+begin_src emacs-lisp

(use-package general
  :config
  (general-evil-setup t)
  (general-create-definer mainkeys
    :states '(normal insert visual emacs)
    :keymaps 'override
    :prefix "SPC" ;; set leader
    :global-prefix "M-SPC")) ;; access leader in insert mode

(elpaca-wait)

#+end_src

*** buffers and bookmarks
#+begin_src elisp

(mainkeys
       "b b"   '(switch-to-buffer :which-key "Switch buffer")
       "b k"   '(kill-current-buffer :which-key "Kill current buffer")
       "b l"   '(bookmark-bmenu-list :which-key "List bookmarks")
       "b n"   '(next-buffer :which-key "Next buffer")
       "b s"   '(bookmark-set :which-key "Set as a bookmark")
       "b w"   '(bookmark-save :which-key "Write bookmarks")
       "b p"   '(previous-buffer :which-key "Previous buffer")
       "b i"   '(ibuffer :which-key "Ibuffer")
       "b B"   '(ibuffer-list-buffers :which-key "Ibuffer list buffers")
       "b K"   '(kill-buffer :which-key "Kill buffer"))

#+end_src

*** files

#+begin_src elisp

(mainkeys
    "d" '(dired-jump :which-key "Launch dired")
    "." '(find-file :which-key "find file")
    "f r" '(counsel-recentf :which-key "find recent file")
    "f s" '(counsel-swiper :which-key "Search in a file")
    "r" '((lambda() (interactive) (load-file "~/.emacs.d/init.el")) :wk "reload emacs")
    "/" '(comment-line :wk "Comment lines"))


#+end_src

*** languages
Changing to secoundrey language only in the current buffer ~so other keybindings would work~

#+begin_src elisp

(mainkeys
    "a" '((lambda () (interactive) (set-input-method 'arabic)) :which-key "Switch to the secound language" )
    "e" '((lambda() (interactive) (set-input-method 'TeX)) :which-key "Switch to english language" ))

#+end_src

*** help !!
need a help ? no problem describe is here
#+begin_src elisp

(mainkeys
"h" '(:ignore t :wk "Help")
   "h f" '(describe-function :wk "Describe function")
   "h v" '(describe-variable :wk "Describe variable"))

#+end_src

* Customaization
** dashboard
welocome screens are usless let's use dashboard instead.

#+BEGIN_SRC emacs-lisp

(use-package dashboard
  :config
  (dashboard-setup-startup-hook)
  ;; icons
  (use-package all-the-icons)
  (use-package nerd-icons)
  (setq dashboard-icon-type 'nerd-icons) ;; use `all-the-icons' package
  (elpaca-wait)

  (setq dashboard-display-icons-p t) ;; icons for the emacs client
  (setq dashboard-set-file-icons t)
  ;; icons for the emacs client
(if (display-graphic-p)
  (setq dashboard-set-file-icons t))
  ;; change title
  (setq dashboard-banner-logo-title "I Love Emacs Games :)")
  (setq dashboard-center-content t) ; make the dashboared centered
  (setq dashboard-items '((recents  . 10)
                        (bookmarks . 5)))
  ; make dasboard work with the emacs client
  (setq initial-buffer-choice (lambda () (get-buffer-create "*dashboard*"))))

#+END_SRC

** fonts
#+BEGIN_SRC emacs-lisp

;; Set default font
(defun nt/set-font-faces()
  (set-face-attribute 'default nil :font "JetBrainsMono Nerd Font 14" :height 150)
  (set-face-attribute 'fixed-pitch nil :font "JetBrainsMono Nerd Font 14" :height 150)
  (set-face-attribute 'variable-pitch nil :font "FantasqueSansM Nerd Font 16" :height 150))
  (set-fontset-font t 'arabic "Omar 16")
;; if the buffer is a daemon it will fix the daemon fonts.
(if (daemonp)
    (add-hook 'after-make-frame-functions
		(lambda (frame)
		  (with-selected-frame frame
		    (nt/set-font-faces))))
  (nt/set-font-faces))

;; Set the default spacing between lines to not make them stuck to each other
(setq-default line-spacing 8)

;; comments in italic
(set-face-attribute 'font-lock-comment-face nil
  :slant 'italic)
(set-face-attribute 'font-lock-keyword-face nil
  :slant 'italic)

#+END_SRC

*** arabic font
by default rtl support in emacs is good but the fonts is not
let's fix that :)

#+BEGIN_SRC emacs-lisp

;; (set-fontset-font "fontset-default"
		  ;; 'arabic
		  ;; (font-spec :family "Omar" :size 16 ))

;; make RTL work will in org mode
(defun set-bidi-env ()
  "interactive"
  (setq bidi-paragraph-direction 'nil))
(add-hook 'org-mode-hook 'set-bidi-env)

#+END_SRC

** noobie bars
if you do use emacs mostly you are a pro chad user who dont want that garbage filling up your screen
use line numbers instead :)

#+BEGIN_SRC emacs-lisp
  
(menu-bar-mode -1)
(tool-bar-mode -1)
(scroll-bar-mode -1)

;; line numbers
(global-display-line-numbers-mode 1)
(global-visual-line-mode t)

#+END_SRC

** theme
installing the whole doom emacs theme and using the doom one theme.

#+begin_src emacs-lisp

  (use-package doom-themes
    :config
    (setq doom-theme-enable-bold t
	  doom-theme-enable-italic t)
    (load-theme 'doom-dracula t) ;; loads the theme
    (doom-themes-org-config))

#+end_src

** modeline
to be honest emacs default modeline is useless.

#+begin_src elisp

  (use-package doom-modeline
    :config
    (doom-modeline-mode 1))

#+end_src

** beacon
never loss your cursor again ;)

#+begin_src elisp

(use-package beacon
:config
(beacon-mode 1))

#+end_src

* emacs tweaks
** ~ files
dear gnu emacs, PLZ stop creating those annoying ~ backup files.

#+begin_src emacs-lisp

(setq backup-directory-alist '((".*" . "~/.local/share/Trash/files")))

#+end_src

** Compiler messages
Dear gnu emacs, can you drop those compiler messages that i dont care about

#+begin_src elisp

(setq comp-async-report-warnings-errors nil)

#+end_src

** symlinks
make emacs always follow symlinks

#+begin_src elisp

(setq vc-handled-backends nil)

#+end_src

** scrolling
scrolling in emacs is just so bad

#+begin_src elisp

(setq scroll-conservatively 101) ;; value greater than 100 gets rid of half page jumping
(setq mouse-wheel-scroll-amount '(3 ((shift) . 3))) ;; how many lines at a time
(setq mouse-wheel-progressive-speed t) ;; accelerate scrolling
(setq mouse-wheel-follow-mouse 't) ;; scroll window under mouse

#+end_src

** zooming in and out
make zomming in/out in emacs ~human friendly~
#+begin_src emacs-lisp

(global-set-key (kbd "C-=") 'text-scale-increase)
(global-set-key (kbd "C--") 'text-scale-decrease)
(global-set-key (kbd "<C-wheel-up>") 'text-scale-increase)
(global-set-key (kbd "<C-wheel-down>") 'text-scale-decrease)

#+end_src

* Ivy and counsel
a completion mechanisem for emacs.

#+begin_src elisp

;; ivy
(use-package ivy
:config (ivy-mode)
(setq ivy-initial-inputs-alist nil))

;; swiper
(use-package swiper
  :after ivy
  :bind (("C-s" . swiper)))

;; counsel
(use-package counsel
:after ivy
:config (counsel-mode))

;; icons :)
(use-package all-the-icons-ivy-rich
  :after all-the-icons
  :init (all-the-icons-ivy-rich-mode 1))

;; ivy-rich
(use-package ivy-rich
  :after ivy
  :custom
  (ivy-virtual-abbreviate 'full
   ivy-rich-switch-buffer-align-virtual-buffer t
   ivy-rich-path-style 'abbrev)
  :config
  (ivy-set-display-transformer 'ivy-switch-buffer
			       'ivy-rich-switch-buffer-transformer)
  (ivy-rich-mode 1)) ;; this gets us descriptions in M-x.

#+end_src

* dired
** icons
let's make dired The best file manager (by adding icons).

#+begin_src elisp

(use-package all-the-icons-dired
  :config
  (add-hook 'dired-mode-hook 'all-the-icons-dired-mode))

#+end_src

** dired-open
uses dired as everything.
#+begin_src emacs-lisp

(use-package dired-open
  :config
  (setq dired-open-extensions '(("gif" . "sxiv")
                                ("jpg" . "sxiv")
                                ("png" . "sxiv")
                                ("mkv" . "mpv")
                                ("mp4" . "mpv"))))

#+end_src

** peep-dired
Can i take a peep plz ?
#+begin_src emacs-lisp

(use-package peep-dired
  :after dired
  :hook (evil-normalize-keymaps . peep-dired-hook))

;; ls command for dired
(setq dired-listing-switches "-alhv --group-directories-first")
;; keybindings
    (evil-define-key 'normal dired-mode-map (kbd "h") 'dired-up-directory) ; using h to go up a directory
    (evil-define-key 'normal dired-mode-map (kbd "l") 'dired-open-file) ; using l to open/enter a/an file/directory 
    (evil-define-key 'normal dired-mode-map (kbd "SPC") 'nil) ; making keybindings start with SPC work in dired
    (evil-define-key 'normal dired-mode-map (kbd "p") 'peep-dired) ; launching peep dired

;; peep-dired keybindings
(evil-define-key 'normal peep-dired-mode-map
  (kbd "j") 'peep-dired-next-file
  (kbd "k") 'peep-dired-prev-file)
(add-hook 'peep-dired-hook 'evil-normalize-keymaps)

#+end_src
** Trash

#+begin_src elisp

(setq delete-by-moving-to-trash t
      trash-directory "~/.local/share/Trash/files/")

#+end_src

* org mode
** org headers
diffrent size for org headers

#+begin_src elisp

(custom-set-faces
 '(org-level-1 ((t (:inherit outline-1 :height 1.7))))
 '(org-level-2 ((t (:inherit outline-2 :height 1.6))))
 '(org-level-3 ((t (:inherit outline-3 :height 1.5))))
 '(org-level-4 ((t (:inherit outline-4 :height 1.4))))
 '(org-level-5 ((t (:inherit outline-5 :height 1.3))))
 '(org-level-6 ((t (:inherit outline-5 :height 1.2))))
 '(org-level-7 ((t (:inherit outline-5 :height 1.1)))))

#+end_src

** org modern
make org header checkboxes markers better

#+begin_src elisp

(use-package org-modern
  :config (global-org-modern-mode 1))
(setq org-hide-emphasis-markers t) ; hide markup signs like ~ ~ * * / / _ _
(setq org-startup-indented t)

#+end_src

** Syntax highlighing
use native syntax highlighting in src code blocks

#+begin_src elisp

(setq org-src-fontify-natively t
    org-src-tab-acts-natively t
    org-confirm-babel-evaluate nil
    org-edit-src-content-indentation 0)

#+end_src

** org tempo
expand tags into src blocks

#+begin_src elisp 

(require 'org-tempo)

#+end_src

** tabel of contents
auto generated table of content 

#+begin_src elisp

(use-package toc-org
  :commands toc-org-enable
  :init (add-hook 'org-mode-hook 'toc-org-enable))

  #+end_src
  
** org auto Tangle
the best plugin for those who wrights litrate configs
when you save the file will auto tangle if you added ~- #+auto_tangle: t -~ in the top of your org file

#+begin_src elisp
(use-package org-auto-tangle
 :defer t
  :hook (org-mode . org-auto-tangle-mode))
#+end_src

** org journal
a good way for journaling (diary) in org mode

#+begin_src elisp

(use-package org-journal
  :defer t
  :init
  ;; Change default prefix key; needs to be set before loading org-journal
  (setq org-journal-prefix-key "C-c j ")
  :config
  (setq org-journal-dir "~/Documents/journal/"
        org-journal-date-format "%A, %d %B %Y"
        org-journal-file-format "%Y-%m-%d.org"))
 #+end_src

** keybindings

#+begin_src elisp

(mainkeys
   "o a" '(org-agenda :which-key "opens org agenda")
   "o w" '(org-agenda-list :which-key "agenda week view")
   "o j" '(org-journal-new-entry :which-key "a new journal file")
   "o c" '(org-journal-open-current-journal-file :which-key "open Current journal file"))

#+end_src

* Magit
the best git client out there.

#+begin_src elisp

(use-package magit
  :config
  (mainkeys :prefix "SPC"
    "g" '(magit-status :which-key "Opens magit")))
(elpaca-wait)

#+end_src

* Which Key
which key is the one of the best emacs packages outh there,
it's like a cheatsheet for keybindings you hit the prefix and which key tells you what next.

#+begin_src emacs-lisp

(use-package which-key
  :config
  (which-key-mode 1)
  (setq which-key-side-window-location 'bottom
	  which-key-sort-order #'which-key-key-order-alpha
	  which-key-sort-uppercase-first nil
	  which-key-add-column-padding 1
	  which-key-max-display-columns nil
	  which-key-min-display-lines 6
	  which-key-side-window-slot -10
	  which-key-side-window-max-height 0.25
	  which-key-idle-delay 0.8
	  which-key-max-description-length 25
	  which-key-allow-imprecise-window-fit t
	  which-key-separator " → " ))

#+end_src

* Emacs IDE
** LSP
language server protocol ~auto complete for code~
#+begin_src elisp

(use-package lsp-mode
  :commands (lsp lsp-deferred)
  :config
  (lsp-enable-which-key-integration t))

;;  lsp-ui UI enhancements for lsp-mode

(use-package lsp-ui
  :hook (lsp-mode . lsp-ui-mode)
  :custom
  (lsp-ui-doc-position 'bottom))

;; Performance tweaks, see
  ;; https://github.com/emacs-lsp/lsp-mode#performance
  (setq gc-cons-threshold 100000000)
  (setq read-process-output-max (* 1024 1024)) ;; 1mb
  (setq lsp-idle-delay 0.500)

#+end_src

*** python
using pyright ~you will need npm installed on your system~
#+begin_src elisp

(use-package lsp-pyright
  :ensure t
  :hook (python-mode . (lambda ()
                          (require 'lsp-pyright)
                          (lsp))))  ; or lsp-deferred
;; pyvenv
(use-package pyvenv
  :ensure t
  :config
  (pyvenv-mode t))

#+end_src

** company
text completion framework
#+begin_src emacs-lisp

(use-package company
  :defer 2
  :after lsp-mode
  :hook (lsp-mode . company-mode)
  :custom
  (company-begin-commands '(self-insert-command))
  (company-idle-delay .1)
  (company-minimum-prefix-length 2)
  (company-show-numbers t)
  (company-tooltip-align-annotations 't)
  (global-company-mode t))

(use-package company-box
  :after company
  :hook (company-mode . company-box-mode))

#+end_src

** Vterm
Terminal emulator in emacs
#+begin_src elisp

(use-package vterm)
(use-package vterm-toggle
  :after vterm
  :config
  (setq vterm-toggle-fullscreen-p nil)
  (setq vterm-toggle-scope 'project)
 (add-to-list 'display-buffer-alist
               '((lambda (buffer-or-name _)
                     (let ((buffer (get-buffer buffer-or-name)))
                       (with-current-buffer buffer
                         (or (equal major-mode 'vterm-mode)
                             (string-prefix-p vterm-buffer-name (buffer-name buffer))))))
                  (display-buffer-reuse-window display-buffer-at-bottom)
                  (reusable-frames . visible)
                  (window-height . 0.3)))
(mainkeys
  "v" '(vterm-toggle :wk "toggle vterm")))
#+end_src

** smartparens
parenthesis auto closing
#+begin_src elisp

(use-package smartparens
  :config (smartparens-global-mode 1))
#+end_src

** sudoedit
edit files as the root user
#+begin_src elisp

(use-package sudo-edit
  :config
    (mainkeys
      "fu" '(sudo-edit-find-file :wk "Sudo find file")
      "fU" '(sudo-edit :wk "Sudo edit file")))

#+end_src

** rainbow mode
show hex color values
#+begin_src elisp

(use-package rainbow-mode
  :config
  (rainbow-mode 1)
  :hook 
  ((org-mode prog-mode) . rainbow-mode))

#+end_src

** Languages support
emacs doesnot support lua :( lets fix that.

#+begin_src emacs-lisp

(use-package lua-mode)
(use-package nix-mode
  :mode "\\.nix\\'")
#+end_src
